### ISSUE TITLE
Bug setting defaults in Diligence email service

### ISSUE THREAD

**Issue by mmilitzer** [tliron/diligence#2]
Hi Tal,

I believe there's a bug in libraries/scripturian/diligence/service/notification/service/email.js. According to my understanding, the "from" email address should be taken from the parameter value - if the parameter is given. Only if no "from" parameter is set, it should fall back to the default configured sender address. 

But the current code does it opposite and therefore the "from" value passed as parameter is always ignored. Here is a patch:

[email_patch.txt](https://github.com/tliron/diligence/files/189457/email_patch.txt)

**Comment by tliron** [comment]
You are correct, thank you for the identification and the fix!
